# Generated by Django 5.0.3 on 2024-05-15 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('servicios_id', models.AutoField(primary_key=True, serialize=False)),
                ('empleado_id', models.IntegerField()),
                ('tipo_servicio', models.CharField(max_length=255)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('producto', models.CharField(max_length=255)),
                ('cantidad_producto', models.IntegerField()),
            ],
            options={
                'db_table': 'servicios',
                'managed': False,
            },
        ),
    ]
