# Generated by Django 5.0.3 on 2024-05-16 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cita'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cita',
            options={'managed': False},
        ),
    ]
