# Generated by Django 5.0.3 on 2024-05-16 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_cita_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cita',
            table='citas',
        ),
    ]
