# Generated by Django 5.0.3 on 2024-05-16 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_cita_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('nombre', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=255)),
                ('contrasena', models.CharField(max_length=255)),
                ('cargo', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('certificados', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'empleados',
                'managed': False,
            },
        ),
    ]
